server:
  port: 8080
spring:
  datasource:
    username: root
    password: Gm_199610
    url: jdbc:mysql://localhost:3306/dawenxi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver